---
include:
  - board: bluemicro840_v1
    shield: kyria_left
  - board: bluemicro840_v1
    shield: kyria_right
  - board: nicenano_v2
    shield: chocolad_left
  - board: nicenano_v2
    shield: chocolad_right