---
include:
  - board: nice_nano_v2
    shield: chocolad_left
  - board: nice_nano_v2
    shield: chocolad_right
  # - board: nice_nano_v2
  #   shield: corne_left
  # - board: nice_nano_v2
  #   shield: corne_right
