---
include:
  # - board: bluemicro840_v1
  #   shield: kyria_left
  # - board: bluemicro840_v1
  #   shield: kyria_right
  - board: nice_nano_v2
    shield: chocolad_left
  - board: nice_nano_v2
    shield: chocolad_right
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
